### ISSUE TITLE
Moving source code (`/src`) as part of pnpm workspace under `packages/unplugin-starter`

### ISSUE THREAD

**Issue by floroz** [unplugin/unplugin-starter#23]
### Clear and concise description of the problem

Currently, the starter template provides a repository with `pnpm workspaces` connected to two projects (`example` and `playground`).

However, the source code of the plugin is not part of the workspace. This means that is not immediately intuitive how to set up E2E testing of the distribution output of the plugin once built.

### Suggested solution

The solution would be to refactor the starting template to create a `packages/` folder where `example` and `playground` will be moved.

Furthermore, the code living in `./src` should be moved to `packages/unplugin-started`.

This may require changes to the root `package.json` to convert it to a fully functional workspace, where besides `example` and `playground`, users can add their own platforms/apps which would consume the distribution of the plugin, to test the artefact shipped to the users.

### Alternative

Since this solution might be somehow opinionated and could introduce the need to run `build --watch` for some of the packages to enable HMR, there could be also a new template being created as `unplugin-starter-workspace`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
> unplugin-starter-workspace

I think that would be better to have a community starter like this. In general, I tend to not introduce monorepo when it's not needed. If we do so by default, it feels like we are advocating monorepo for unplugins, which I think it's not necessary for majority of the plugins.

/cc @sxzz WDYT?

**Comment by floroz** [comment]
> > unplugin-starter-workspace
> 
> I think that would be better to have a community starter like this. In general, I tend to not introduce monorepo when it's not needed. If we do so by default, it feels like we are advocating monorepo for unplugins, which I think it's not necessary for majority of the plugins.
> 
> /cc @sxzz WDYT?

Yes, as I was finishing writing my proposal I also realised that the change might be too opinionated for the vast majority of users.

@antfu, It would be great to leverage the huge experience you and @sxzz have in setting up such projects, to create a new starting template (`unplugin-starter-workspaces`) for a multi-package repo hosting a collection of unplugins.

It could also have `packages/unplugin-starter-1` and `packages/unplugin-starter-2` to make it explicit that such monorepo could host multiple unplugins and orchestrate the building and publishing of all of them.

**Comment by antfu** [comment]
I think that would be going a bit too far. I think it won't be common to have multiple unplugins in a monorepo (as you can see in this org). It would fall into the field of teaching ppl how to do a proper monorepo, which is out-of-scope of neither the unplugin nor the starter template. We'll leave it to the community then. Thanks.

**Comment by floroz** [comment]
Make sense. Thank you @antfu for reviewing the issue and the proposal.
